### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by nielsbom** [lassebomh/htmx-sandbox#1]
Hi,

I'm currently getting a blank screen when I load https://lassebomh.github.io/htmx-sandbox/

**Comment by lassebomh** [comment]
Is it still broken if you open it in incognito mode? And what does the console say?

**Comment by nielsbom** [comment]
I tried it in non-incognito Chrome where I get this error:
![Screenshot 2022-12-21 _17 37 24](https://user-images.githubusercontent.com/327080/208957524-493920fa-cdab-42d6-b8a9-a23dbac00263.png)

In Incognito Chrome and regular Firefox I do see something. So I guess it's an interaction with one of my Chrome extensions.

If you want I can send you a list of the extensions I'm using.

**Comment by lassebomh** [comment]
Nice, I was hoping that was the case :) I'd be happy to get the list
